### ISSUE TITLE
ArgumentOutOfRangeException when adding GroupStyle at runtime

### ISSUE THREAD

**Issue by myCollections** [sbaeumlisberger/VirtualizingWrapPanel#68]
Hello,

Sometime i get this error using WrapPanel :

```
at System.ThrowHelper.ThrowArgumentOutOfRange_IndexMustBeLessException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at MS.Internal.ListOfObject.System.Collections.Generic.IList<System.Object>.get_Item(Int32 index)
   at WpfToolkit.Controls.ItemContainerManager.Virtualize(UIElement container)
   at WpfToolkit.Controls.VirtualizingWrapPanel.VirtualizeItemsAfterEndIndex()
   at WpfToolkit.Controls.VirtualizingWrapPanel.RealizeAndVirtualizeItems()
   at WpfToolkit.Controls.VirtualizingWrapPanel.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Any clue on how to fix it ?

Thanks for your time and great work.

Regards

Jeff

**Comment by sbaeumlisberger** [comment]
Hello, do you have more information under what conditions or in what scenarios this happens? Without a reproduction it will be difficult to help.

**Comment by myCollections** [comment]
Thanks for your quick answser.

I have this liste box 

```
<ListBox  Name="MainStack" KeyboardNavigation.TabNavigation="Cycle" SelectionChanged="MainStack_SelectionChanged" 
            MouseDoubleClick="MainStack_MouseDoubleClick" Margin="5,0,0,0" SelectionMode="Extended" ScrollViewer.HorizontalScrollBarVisibility="Disabled"
            VirtualizingPanel.CacheLengthUnit="Item" VirtualizingPanel.CacheLength="8,8" VirtualizingPanel.ScrollUnit="Pixel" ScrollViewer.IsDeferredScrollingEnabled="False"
            VirtualizingPanel.VirtualizationMode="Standard" VirtualizingPanel.IsVirtualizingWhenGrouping="True"
            ItemTemplate="{StaticResource CoverTemplate}" ItemsSource="{Binding}" ItemContainerStyle="{DynamicResource ListBoxCoverItem}">
    <ListBox.ItemsPanel>
        <ItemsPanelTemplate>
            <wpftk:VirtualizingWrapPanel />
        </ItemsPanelTemplate>
    </ListBox.ItemsPanel>
    <ListBox.ContextMenu>
        <ContextMenu>
            <MenuItem Header="{DynamicResource AddApps}" Click="mniAddApps_Click"  ToolTip="{DynamicResource AddNewApplication}"/>
            <MenuItem Header="{DynamicResource AddBook}" Click="mniAddBooks_Click" ToolTip="{DynamicResource AddNewBook}"/>
            <MenuItem Header="{DynamicResource AddGames}" Click="mniAddGamez_Click" ToolTip="{DynamicResource AddNewGame}"/>
            <MenuItem Header="{DynamicResource AddMedia}" Click="mniAddMedia_Click" ToolTip="{DynamicResource AddNewMedia}"/>
            <MenuItem Header="{DynamicResource AddMovie}" Click="mniAddMovie_Click" ToolTip="{DynamicResource AddNewMovie}"/>
            <MenuItem Header="{DynamicResource AddMusic}" Click="mniAddMusic_Click" ToolTip="{DynamicResource AddNewMusic}"/>
            <MenuItem Header="{DynamicResource AddNds}" Click="mniAddNds_Click" ToolTip="{DynamicResource AddNewNDS}"/>
            <MenuItem Header="{DynamicResource AddSeries}" Click="mniAddSeries_Click" ToolTip="{DynamicResource AddNewSeries}"/>
            <MenuItem Header="{DynamicResource AddXXX}" Click="mniAddXXX_Click" ToolTip="{DynamicResource AddNewXXX}"/>
        </ContextMenu>
    </ListBox.ContextMenu>
</ListBox>
```
Everything is working find, but when i use this groupestyle i get the outofrange excpetions
```

        <GroupStyle x:Key="groupStyle">
            <GroupStyle.ContainerStyle>
                <Style TargetType="{x:Type GroupItem}">
                    <Setter Property="Template">
                        <Setter.Value>
                            <ControlTemplate TargetType="{x:Type GroupItem}">
                                <Grid>
                                    <Grid.RowDefinitions>
                                        <RowDefinition />
                                        <RowDefinition />
                                    </Grid.RowDefinitions>
                                    <Grid.ContextMenu>
                                        <ContextMenu>
                                            <ContextMenu.Effect>
                                                <DropShadowEffect/>
                                            </ContextMenu.Effect>
                                            <MenuItem Header="{DynamicResource OpenAll}" Click="OpenAll_Click"  IsCheckable="False"/>
                                            <MenuItem Header="{DynamicResource CloseAll}" Click="CloseAll_Click" IsCheckable="False"/>
                                        </ContextMenu>
                                    </Grid.ContextMenu>
                                    <Grid Height="26" VerticalAlignment="Center" Background="{DynamicResource MahApps.Brushes.Accent2}">
                                        <Grid.Resources>
                                            <Style TargetType="{x:Type TextBlock}">
                                                <Setter Property="Foreground" Value="{DynamicResource MahApps.Brushes.Text}" />
                                                <Setter Property="VerticalAlignment" Value="Center" />
                                            </Style>
                                        </Grid.Resources>
                                        <Grid.ColumnDefinitions>
                                            <ColumnDefinition Width="Auto" />
                                            <ColumnDefinition Width="*" />
                                            <ColumnDefinition Width="45" />
                                            <ColumnDefinition Width="50" />
                                        </Grid.ColumnDefinitions>

                                        <ToggleButton Grid.Column="0" x:Name="btnShowHide" IsChecked="False" Margin="3.5" />
                                        <TextBlock Grid.Column="1" Text="{Binding Path=Name}" Margin="3.5,0" />
                                        <TextBlock Grid.Column="2" Text="Count:" />
                                        <TextBlock Grid.Column="3" Text="{Binding Path=ItemCount}"  TextAlignment="Right" Margin="0,0,11,0" />

                                    </Grid>

                                    <ItemsPresenter Visibility="{Binding ElementName=btnShowHide, Path=IsChecked, Converter={StaticResource booleanToVisibilityConverter}}" Grid.Row="1" Margin="11,0,0,3.5" />

                                </Grid>
                            </ControlTemplate>
                        </Setter.Value>
                    </Setter>
                </Style>
            </GroupStyle.ContainerStyle>
        </GroupStyle>

```

**Comment by sbaeumlisberger** [comment]
Okay, I will take a look.

**Comment by sbaeumlisberger** [comment]
Should be fixed. I will be releasing a new nuget package soon.

**Comment by myCollections** [comment]
Wow, thanks a lot.

I will let you know how it works

**Comment by sbaeumlisberger** [comment]
The nuget package is now available: https://www.nuget.org/packages/VirtualizingWrapPanel/2.1.0

**Comment by myCollections** [comment]
Works fine, thanks a lot
